export const seedBengkels = [
  {
    id: "b1",
    nama: "Bengkel Maju Jaya Motor",
    alamat: "Jl. Warung Buncit Raya No. 45, Jakarta Selatan",
    lat: -6.2625,
    lng: 106.8237,
    jamBuka: "08:00 - 17:00",
    rating: 4.5,
    spesialisasi: ["Motor Matic", "Motor Bebek", "Servis Ringan"],
    foto: "/images/bengkels/b1.jpg",
  },
  {
    id: "b2",
    nama: "Auto Care Pro",
    alamat: "Jl. Cipete Raya No. 12, Jakarta Selatan",
    lat: -6.275,
    lng: 106.7955,
    jamBuka: "08:00 - 20:00",
    rating: 4.7,
    spesialisasi: ["Mobil", "AC Mobil", "Tune Up", "Turun Mesin"],
    foto: "/images/bengkels/b2.jpg",
  },
  {
    id: "b3",
    nama: "Bengkel Berkah Motor",
    alamat: "Jl. Raya Bogor KM 28, Jakarta Timur",
    lat: -6.3385,
    lng: 106.882,
    jamBuka: "07:30 - 16:30",
    rating: 4.1,
    spesialisasi: ["Motor Sport", "Servis Injeksi", "Modifikasi"],
    foto: "/images/bengkels/b3.jpg",
  },
  {
    id: "b4",
    nama: "Prima Auto Service",
    alamat: "Jl. Fatmawati Raya No. 88, Jakarta Selatan",
    lat: -6.245,
    lng: 106.825,
    jamBuka: "08:00 - 18:00",
    rating: 4.3,
    spesialisasi: ["Mobil Keluarga", "Servis Rem", "Ganti Ban", "Spooring"],
    foto: "/images/bengkels/b4.jpg",
  },
  {
    id: "b5",
    nama: "Speed Garage",
    alamat: "Jl. Pluit Karang No. 7, Jakarta Utara",
    lat: -6.157,
    lng: 106.905,
    jamBuka: "09:00 - 21:00",
    rating: 4.6,
    spesialisasi: ["Motor", "Mobil", "AC", "Kaki-kaki", "Ganti Oli"],
    foto: "/images/bengkels/b5.jpg",
  },
]
