export const seedMekaniks = [
  {
    id: "m1",
    nama: "Budi Santoso",
    foto: "/images/mekaniks/m1.jpg",
    bengkelId: "b1",
    platKendaraan: "B 1234 XYZ",
    sertifikasi: ["Teknisi Motor", "Servis Injeksi"],
    rating: 4.7,
    jumlahUlasan: 128,
    jarak: 3,
    spesialisasi: ["Motor Matic", "Servis Ringan", "Ganti Oli"],
  },
  {
    id: "m2",
    nama: "Andi Pratama",
    foto: "/images/mekaniks/m2.jpg",
    bengkelId: "b1",
    platKendaraan: "B 2345 ABC",
    sertifikasi: ["Teknisi Motor", "Kelistrikan"],
    rating: 4.5,
    jumlahUlasan: 95,
    jarak: 4,
    spesialisasi: ["Motor Bebek", "Kelistrikan", "Busi"],
  },
  {
    id: "m3",
    nama: "Rudi Hartono",
    foto: "/images/mekaniks/m3.jpg",
    bengkelId: "b2",
    platKendaraan: "B 3456 DEF",
    sertifikasi: ["Teknisi Mobil", "AC Mobil", "Turun Mesin"],
    rating: 4.9,
    jumlahUlasan: 210,
    jarak: 5,
    spesialisasi: ["Mobil", "AC Mobil", "Turun Mesin", "Tune Up"],
  },
  {
    id: "m4",
    nama: "Dimas Ardian",
    foto: "/images/mekaniks/m4.jpg",
    bengkelId: "b2",
    platKendaraan: "B 4567 GHI",
    sertifikasi: ["Teknisi Mobil"],
    rating: 4.3,
    jumlahUlasan: 67,
    jarak: 6,
    spesialisasi: ["Mobil", "Servis Rem", "Kaki-kaki"],
  },
  {
    id: "m5",
    nama: "Hendra Gunawan",
    foto: "/images/mekaniks/m5.jpg",
    bengkelId: "b3",
    platKendaraan: "B 5678 JKL",
    sertifikasi: ["Teknisi Motor", "Modifikasi"],
    rating: 4.1,
    jumlahUlasan: 43,
    jarak: 8,
    spesialisasi: ["Motor Sport", "Modifikasi", "Servis Injeksi"],
  },
  {
    id: "m6",
    nama: "Fajar Nugroho",
    foto: "/images/mekaniks/m6.jpg",
    bengkelId: "b4",
    platKendaraan: "B 6789 MNO",
    sertifikasi: ["Teknisi Mobil", "Spooring & Balancing"],
    rating: 4.6,
    jumlahUlasan: 156,
    jarak: 2,
    spesialisasi: ["Mobil Keluarga", "Ganti Ban", "Spooring", "Servis Rem"],
  },
  {
    id: "m7",
    nama: "Rizky Setiawan",
    foto: "/images/mekaniks/m7.jpg",
    bengkelId: "b5",
    platKendaraan: "B 7890 PQR",
    sertifikasi: ["Teknisi Motor & Mobil", "AC", "Kelistrikan"],
    rating: 4.8,
    jumlahUlasan: 189,
    jarak: 7,
    spesialisasi: ["Motor", "Mobil", "AC", "Kaki-kaki", "Ganti Oli"],
  },
]
