export const seedServices = [
  {
    id: "sv1",
    nama: "Servis Ringan",
    deskripsi: "Servis rutin meliputi ganti oli, cek filter, dan pemeriksaan umum kendaraan",
    hargaJasa: 150000,
    estimasiWaktu: "60 menit",
    ikon: "Wrench",
  },
  {
    id: "sv2",
    nama: "Ganti Oli",
    deskripsi: "Penggantian oli mesin dengan oli berkualitas sesuai spesifikasi kendaraan",
    hargaJasa: 75000,
    estimasiWaktu: "30 menit",
    ikon: "Droplets",
  },
  {
    id: "sv3",
    nama: "Turun Mesin",
    deskripsi: "Overhaul mesin menyeluruh untuk kerusakan berat pada komponen internal mesin",
    hargaJasa: 850000,
    estimasiWaktu: "3 hari",
    ikon: "Cog",
  },
  {
    id: "sv4",
    nama: "Servis Rem",
    deskripsi: "Pemeriksaan dan penggantian kampas rem, pengecekan sistem pengereman",
    hargaJasa: 200000,
    estimasiWaktu: "90 menit",
    ikon: "CircleDot",
  },
  {
    id: "sv5",
    nama: "Tune Up",
    deskripsi: "Penyetelan mesin termasuk busi, karburator/injeksi, dan sistem pengapian",
    hargaJasa: 250000,
    estimasiWaktu: "2 jam",
    ikon: "Gauge",
  },
  {
    id: "sv6",
    nama: "Servis AC",
    deskripsi: "Perawatan dan perbaikan sistem AC kendaraan termasuk isi freon",
    hargaJasa: 300000,
    estimasiWaktu: "2 jam",
    ikon: "Wind",
  },
  {
    id: "sv7",
    nama: "Ganti Ban",
    deskripsi: "Penggantian ban luar dan dalam, termasuk balancing dan spooring",
    hargaJasa: 100000,
    estimasiWaktu: "45 menit",
    ikon: "Circle",
  },
  {
    id: "sv8",
    nama: "Servis Injeksi",
    deskripsi: "Pembersihan dan kalibrasi sistem injeksi bahan bakar",
    hargaJasa: 350000,
    estimasiWaktu: "90 menit",
    ikon: "Zap",
  },
]
